# ============================================
# IHSG STOCKS LIST - FULL COMPREHENSIVE
# ============================================
# Format: Yahoo Finance ticker with .JK suffix

IHSG_STOCKS = [
    # === EXISTING USER REQUESTED (PRIORITY) ===
    "BUMI.JK", "DEWA.JK", "ANTM.JK", "BBCA.JK", "BBRI.JK",
    "BMRI.JK", "BRMS.JK", "INET.JK", "PTRO.JK", "ADRO.JK",
    "RAJA.JK", "ARCI.JK", "SUPA.JK", "BUVA.JK", "BULL.JK",
    "GOTO.JK", "MINA.JK", "MBMA.JK", "ASII.JK", "TLKM.JK",
    "AMMN.JK", "MDKA.JK", "BRPT.JK", "INCO.JK", "DSSA.JK",
    "TINS.JK", "BKSL.JK", "BBNI.JK", "UNTR.JK", "WIFI.JK",
    "CDIA.JK", "NCKL.JK", "IMPC.JK", "ENRG.JK", "RATU.JK",
    "ADMR.JK", "PANI.JK", "CUAN.JK", "EMAS.JK", "INDY.JK",
    "GTSI.JK", "HRTA.JK", "BIPI.JK", "KIJA.JK", "RMKE.JK",
    "HUMI.JK", "MEDC.JK", "CBDK.JK", "NICL.JK", "COIN.JK",
    "OASA.JK", "EMTK.JK", "EXCL.JK", "BREN.JK", "JPFA.JK",
    "TOBA.JK", "PNLF.JK", "INKP.JK", "VKTR.JK", "PSAB.JK",
    "PADI.JK", "TCPI.JK", "AADI.JK", "PWON.JK", "PGAS.JK",
    "RLCO.JK", "BBYB.JK", "CPRO.JK", "HRUM.JK", "TRIN.JK",
    "UNVR.JK", "INDF.JK", "LEAD.JK", "TRUE.JK", "ITMA.JK",
    "PSKT.JK", "SMDR.JK", "KLBF.JK", "ICBP.JK", "SSIA.JK",
    "BBKP.JK", "PGEO.JK", "KETR.JK", "BRIS.JK", "SINI.JK",
    "AMRT.JK", "IRSX.JK", "LPKR.JK", "TPIA.JK", "PADA.JK",
    "NRCA.JK", "SCMA.JK", "COAL.JK", "ZATA.JK", "IATA.JK",
    "DKFT.JK", "BNBR.JK", "SOCI.JK", "ISAT.JK", "ELTY.JK",
    "REAL.JK", "PTBA.JK", "PBSA.JK", "PIPA.JK", "PPRE.JK",
    "KPIG.JK", "SMIL.JK", "CPIN.JK", "PJHB.JK", "ESSA.JK",
    "HMSP.JK", "BBTN.JK", "SRTG.JK", "TEBE.JK", "FILM.JK",
    "TOWR.JK", "DOOH.JK", "DATA.JK", "AKRA.JK", "CTRA.JK",
    "DSNG.JK", "SMGR.JK", "MBSS.JK", "MORA.JK", "MHKI.JK",
    "FUTR.JK", "INPC.JK", "ITMG.JK", "MAPI.JK", "GOLF.JK",
    "SGER.JK", "ASLI.JK", "ASHA.JK", "AHAP.JK", "CBRE.JK",
    "CYBR.JK", "JARR.JK", "MLPL.JK", "PTPP.JK", "SMRA.JK",
    "GGRM.JK", "BWPT.JK", "MYOR.JK", "MTEL.JK", "ELIT.JK",
    "JSMR.JK", "CMNT.JK", "ARKO.JK", "BUKA.JK", "VICI.JK",
    "TBIG.JK", "ELSA.JK", "FOLK.JK", "MEJA.JK", "WIRG.JK",
    "MAHA.JK", "BELL.JK", "MSIN.JK", "NETV.JK", "TAPG.JK",
    "INDO.JK", "ASRI.JK", "TOSK.JK", "KLAS.JK", "DAAZ.JK",
    "KEEN.JK", "NINE.JK", "PNBN.JK", "OPMS.JK", "BBRM.JK",
    "MARK.JK", "FIRE.JK", "UNIQ.JK", "AYAM.JK", "STRK.JK",
    "FAST.JK", "PACK.JK", "BMTR.JK", "TMAS.JK", "BACA.JK",
    "ERAA.JK", "BSDE.JK", "COCO.JK", "DMAS.JK", "TRON.JK",
    "SLIS.JK", "PYFA.JK", "TKIM.JK", "KDTN.JK", "ARTO.JK",
    "SOLA.JK", "KRAS.JK", "SGRO.JK", "MAPA.JK", "APEX.JK",
    "NSSS.JK", "DSFI.JK", "KOCI.JK", "BSBK.JK", "GIAA.JK",
    "GMFI.JK", "SMGA.JK", "INTP.JK", "UANG.JK", "HOPE.JK",
    "WIIM.JK", "SMKM.JK", "ASSA.JK", "IKAN.JK",
    "BGTG.JK", "BOAT.JK", "FPNI.JK", "HATM.JK", "JGLE.JK",
    "RMKO.JK", "HDIT.JK", "DEWI.JK", "KOKA.JK", "WOWS.JK",
    "ATLA.JK", "ACES.JK", "MNCN.JK", "MSKY.JK", "BEEF.JK",
    "IMJS.JK", "BFIN.JK", "UDNG.JK", "CMRY.JK", "ERAL.JK",
    "MMIX.JK", "JAST.JK",

    # === NEW ADDITIONS (564 stocks) ===
    "AALI.JK", "ABMM.JK", "ACRO.JK", "ACST.JK", "ADCP.JK",
    "ADES.JK", "ADHI.JK", "ADMF.JK", "ADMG.JK", "AEGS.JK",
    "AGAR.JK", "AGII.JK", "AGRO.JK", "AGRS.JK", "AIMS.JK",
    "AISA.JK", "AKPI.JK", "AKSI.JK", "ALDO.JK", "ALII.JK",
    "ALKA.JK", "AMAG.JK", "AMAN.JK", "AMAR.JK", "AMFG.JK",
    "AMIN.JK", "AMMS.JK", "AMOR.JK", "ANJT.JK", "APIC.JK",
    "APII.JK", "APLI.JK", "APLN.JK", "AREA.JK", "ARGO.JK",
    "ARII.JK", "ARNA.JK", "ARTA.JK", "ASBI.JK", "ASDM.JK",
    "ASGR.JK", "ASJT.JK", "ASLC.JK", "ASPI.JK", "ASPR.JK",
    "ASRM.JK", "ATIC.JK", "AUTO.JK", "AVIA.JK", "AWAN.JK",
    "AXIO.JK", "AYLS.JK", "BABP.JK", "BABY.JK", "BAIK.JK",
    "BAJA.JK", "BALI.JK", "BANK.JK", "BAPA.JK", "BATR.JK",
    "BAYU.JK", "BBHI.JK", "BBLD.JK", "BBMD.JK", "BBSI.JK",
    "BBSS.JK", "BCAP.JK", "BCIC.JK", "BCIP.JK", "BDKR.JK",
    "BDMN.JK", "BEER.JK", "BESS.JK", "BEST.JK", "BHAT.JK",
    "BIKE.JK", "BINA.JK", "BINO.JK", "BIRD.JK", "BISI.JK",
    "BJBR.JK", "BJTM.JK", "BKSW.JK", "BLES.JK", "BLOG.JK",
    "BLUE.JK", "BMAS.JK", "BMBL.JK", "BMHS.JK", "BMSR.JK",
    "BNBA.JK", "BNGA.JK", "BNII.JK", "BNLI.JK", "BOBA.JK",
    "BOGA.JK", "BOLA.JK", "BOLT.JK", "BPFI.JK", "BPII.JK",
    "BPTR.JK", "BRAM.JK", "BRNA.JK", "BRRC.JK", "BSIM.JK",
    "BSML.JK", "BSSR.JK", "BTON.JK", "BTPN.JK", "BTPS.JK",
    "BUAH.JK", "BUDI.JK", "BUKK.JK", "BVIC.JK", "BYAN.JK",
    "CAKK.JK", "CAMP.JK", "CARE.JK", "CARS.JK", "CASA.JK",
    "CASH.JK", "CASS.JK", "CBPE.JK", "CBUT.JK", "CCSI.JK",
    "CEKA.JK", "CENT.JK", "CFIN.JK", "CGAS.JK", "CHEK.JK",
    "CHEM.JK", "CHIP.JK", "CINT.JK", "CITA.JK", "CITY.JK",
    "CLAY.JK", "CLEO.JK", "CLPI.JK", "CMNP.JK", "CNMA.JK",
    "CRAB.JK", "CRSN.JK", "CSAP.JK", "CSIS.JK", "CSMI.JK",
    "CSRA.JK", "CTBN.JK", "CTTH.JK", "DADA.JK", "DART.JK",
    "DAYA.JK", "DCII.JK", "DEFI.JK", "DEPO.JK", "DFAM.JK",
    "DGIK.JK", "DGNS.JK", "DGWG.JK", "DILD.JK", "DIVA.JK",
    "DKHH.JK", "DLTA.JK", "DMMX.JK", "DMND.JK", "DNAR.JK",
    "DNET.JK", "DOID.JK", "DOSS.JK", "DPNS.JK", "DPUM.JK",
    "DRMA.JK", "DUTI.JK", "DVLA.JK", "DWGL.JK", "DYAN.JK",
    "EAST.JK", "ECII.JK", "EDGE.JK", "EKAD.JK", "ELPI.JK",
    "EMDE.JK", "ENAK.JK", "EPMT.JK", "ERTX.JK", "ESIP.JK",
    "ESTA.JK", "ESTI.JK", "EURO.JK", "FAPA.JK", "FISH.JK",
    "FITT.JK", "FLMC.JK", "FMII.JK", "FORE.JK", "FORU.JK",
    "FUJI.JK", "FWCT.JK", "GDST.JK", "GDYR.JK", "GEMA.JK",
    "GEMS.JK", "GGRP.JK", "GHON.JK", "GJTL.JK", "GLVA.JK",
    "GMTD.JK", "GOLD.JK", "GOOD.JK", "GPRA.JK", "GPSO.JK",
    "GRIA.JK", "GRPH.JK", "GSMF.JK", "GTBO.JK", "GTRA.JK",
    "GULA.JK", "GUNA.JK", "GWSA.JK", "GZCO.JK", "HAIS.JK",
    "HAJJ.JK", "HALO.JK", "HBAT.JK", "HDFA.JK", "HEAL.JK",
    "HELI.JK", "HERO.JK", "HEXA.JK", "HGII.JK", "HILL.JK",
    "HOKI.JK", "HOMI.JK", "HYGN.JK", "IBOS.JK", "IDEA.JK",
    "IDPR.JK", "IFII.JK", "IFSH.JK", "IGAR.JK", "IKBI.JK",
    "IKPM.JK", "IMAS.JK", "INAI.JK", "INCI.JK", "INDR.JK",
    "INDS.JK", "INDX.JK", "INOV.JK", "INPP.JK", "INRU.JK",
    "INTD.JK", "IOTF.JK", "IPAC.JK", "IPCC.JK", "IPCM.JK",
    "IPOL.JK", "IRRA.JK", "ISAP.JK", "ISEA.JK", "ISSP.JK",
    "ITIC.JK", "JATI.JK", "JAWA.JK", "JAYA.JK", "JECC.JK",
    "JIHD.JK", "JKON.JK", "JMAS.JK", "JRPT.JK", "JSPT.JK",
    "JTPE.JK", "KAEF.JK", "KAQI.JK", "KBLI.JK", "KBLM.JK",
    "KBLV.JK", "KDSI.JK", "KEJU.JK", "KICI.JK", "KING.JK",
    "KINO.JK", "KIOS.JK", "KJEN.JK", "KKGI.JK", "KLIN.JK",
    "KMDS.JK", "KMTR.JK", "KOBX.JK", "KONI.JK", "KOPI.JK",
    "KRYA.JK", "KSIX.JK", "KUAS.JK", "LABA.JK", "LABS.JK",
    "LAJU.JK", "LAPD.JK", "LCKM.JK", "LFLO.JK", "LIFE.JK",
    "LINK.JK", "LION.JK", "LIVE.JK", "LMAX.JK", "LMPI.JK",
    "LOPI.JK", "LPCK.JK", "LPGI.JK", "LPIN.JK", "LPLI.JK",
    "LPPF.JK", "LPPS.JK", "LRNA.JK", "LSIP.JK", "LTLS.JK",
    "LUCK.JK", "LUCY.JK", "MAIN.JK", "MANG.JK", "MAPB.JK",
    "MASB.JK", "MAXI.JK", "MAYA.JK", "MBAP.JK", "MBTO.JK",
    "MCAS.JK", "MCOL.JK", "MCOR.JK", "MDIY.JK", "MDKI.JK",
    "MDLA.JK", "MDLN.JK", "MEDS.JK", "MEGA.JK", "MENN.JK",
    "MERI.JK", "MERK.JK", "MGLV.JK", "MGNA.JK", "MGRO.JK",
    "MICE.JK", "MIDI.JK", "MIKA.JK", "MINE.JK", "MITI.JK",
    "MKAP.JK", "MKPI.JK", "MKTR.JK", "MLBI.JK", "MLIA.JK",
    "MLPT.JK", "MMLP.JK", "MOLI.JK", "MPIX.JK", "MPMX.JK",
    "MPOW.JK", "MPPA.JK", "MPRO.JK", "MPXL.JK", "MRAT.JK",
    "MREI.JK", "MSIE.JK", "MSJA.JK", "MSTI.JK", "MTDL.JK",
    "MTLA.JK", "MTMH.JK", "MTWI.JK", "MUTU.JK", "MYOH.JK",
    "NAIK.JK", "NANO.JK", "NASI.JK", "NATO.JK", "NAYZ.JK",
    "NELY.JK", "NEST.JK", "NFCX.JK", "NICE.JK", "NICK.JK",
    "NIKL.JK", "NIRO.JK", "NISP.JK", "NOBU.JK", "NPGF.JK",
    "NTBK.JK", "NZIA.JK", "OBAT.JK", "OBMD.JK", "OILS.JK",
    "OKAS.JK", "OLIV.JK", "OMED.JK", "PALM.JK", "PAMG.JK",
    "PANR.JK", "PANS.JK", "PART.JK", "PBID.JK", "PDES.JK",
    "PDPP.JK", "PEGE.JK", "PEHA.JK", "PEVE.JK", "PGJO.JK",
    "PGLI.JK", "PGUN.JK", "PICO.JK", "PJAA.JK", "PKPK.JK",
    "PLAN.JK", "PMJS.JK", "PMUI.JK", "PNBS.JK", "PNGO.JK",
    "PNIN.JK", "PNSE.JK", "POLU.JK", "PORT.JK", "POWR.JK",
    "PPGL.JK", "PPRI.JK", "PRAY.JK", "PRDA.JK", "PRIM.JK",
    "PSAT.JK", "PSDN.JK", "PSGO.JK", "PSSI.JK", "PTIS.JK",
    "PTMP.JK", "PTPS.JK", "PTPW.JK", "PTSN.JK", "PTSP.JK",
    "PUDP.JK", "PURI.JK", "PZZA.JK", "RAAM.JK", "RALS.JK",
    "RANC.JK", "RCCC.JK", "RDTX.JK", "RELF.JK", "RELI.JK",
    "RGAS.JK", "RIGS.JK", "RISE.JK", "ROCK.JK", "RONY.JK",
    "ROTI.JK", "RSCH.JK", "RUIS.JK", "RUNS.JK", "SAFE.JK",
    "SAME.JK", "SAMF.JK", "SAPX.JK", "SATU.JK", "SBMA.JK",
    "SCCO.JK", "SCNP.JK", "SDMU.JK", "SDPC.JK", "SDRA.JK",
    "SEMA.JK", "SFAN.JK", "SHID.JK", "SHIP.JK", "SICO.JK",
    "SIDO.JK", "SILO.JK", "SIMP.JK", "SKBM.JK", "SKLT.JK",
    "SKRN.JK", "SMAR.JK", "SMBR.JK", "SMDM.JK", "SMKL.JK",
    "SMLE.JK", "SMMA.JK", "SMMT.JK", "SMSM.JK", "SNLK.JK",
    "SOFA.JK", "SOHO.JK", "SONA.JK", "SOTS.JK", "SOUL.JK",
    "SPMA.JK", "SPRE.JK", "SPTO.JK", "SRAJ.JK", "SRSN.JK",
    "SSMS.JK", "SSTM.JK", "STAA.JK", "STAR.JK", "STTP.JK",
    "SULI.JK", "SUNI.JK", "SURE.JK", "SURI.JK", "SWID.JK",
    "TALF.JK", "TAYS.JK", "TBLA.JK", "TBMS.JK", "TCID.JK",
    "TFAS.JK", "TGKA.JK", "TIFA.JK", "TIRA.JK", "TLDN.JK",
    "TMPO.JK", "TNCA.JK", "TOOL.JK", "TOTL.JK", "TOTO.JK",
    "TPMA.JK", "TRGU.JK", "TRIM.JK", "TRIS.JK", "TRJA.JK",
    "TRST.JK", "TRUK.JK", "TRUS.JK", "TSPC.JK", "TUGU.JK",
    "TYRE.JK", "UCID.JK", "UFOE.JK", "ULTJ.JK", "UNIC.JK",
    "UNIT.JK", "UNTD.JK", "URBN.JK", "UVCR.JK", "VAST.JK",
    "VERN.JK", "VICO.JK", "VINS.JK", "VISI.JK", "VOKS.JK",
    "VRNA.JK", "VTNY.JK", "WAPO.JK", "WEGE.JK", "WEHA.JK",
    "WGSH.JK", "WIDI.JK", "WINE.JK", "WINS.JK", "WOMF.JK",
    "WOOD.JK", "WTON.JK", "YELO.JK", "YOII.JK", "YPAS.JK",
    "YULE.JK", "YUPI.JK", "ZONE.JK"
]

def get_all_stocks():
    """Return list of all IHSG stocks (Unique)"""
    return sorted(list(set(IHSG_STOCKS)))

def get_stock_count():
    """Return total number of stocks"""
    return len(get_all_stocks())
